Controllers/AdminFnController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using practice_mvc02.filters;
using practice_mvc02.Models;
using practice_mvc02.Models.dataTable;
using practice_mvc02.Repositories;

namespace practice_mvc02.Controllers
{
    [TypeFilter(typeof(ActionFilter))]
    public class AdminFnController : BaseController
    {
        public AdminFnRepository aRepository { get; }
        public MasterRepository mRepository { get; }
        public PunchCardRepository pRepository { get; }
        private ChkPunchLogWarn chkWarn { get; }
        private CalWorkTime calTime { get; }
        private CalAnnualLeave calAnnual { get; }
        
        public AdminFnController(AdminFnRepository a_repository, MasterRepository m_repository,
                                PunchCardRepository p_repository, AnnualLeaveRepository al_repository,
                                ApplyOvertimeRepository ap_repository, 
                                IHttpContextAccessor httpContextAccessor):base(httpContextAccessor)                
        {
            this.aRepository = a_repository;
            this.mRepository = m_repository;
            this.pRepository = p_repository;
            this.chkWarn = new ChkPunchLogWarn(p_repository, httpContextAccessor);
            this.calTime = new CalWorkTime(p_repository, ap_repository, httpContextAccessor);
            this.calAnnual = new CalAnnualLeave(al_repository);
        }

        public IActionResult Index(string page="operateLog")
        {           
            return selectPage(page);
        }

        public IActionResult selectPage(string page){
            ViewBag.ruleVal = ruleVal;
            ViewBag.Auth = "Y";
            ViewBag.ID = (int)loginID;
            ViewBag.loginAccLV = loginAccLV;
            ViewBag.Page = page;
            return View("AdminFnPage");
        }

        public List<ViewOpLog> getOperateLog(OpLogFilter filter){
            filter.eDate = filter.eDate.AddDays(1);
            filter.active = String.IsNullOrEmpty(filter.active)? "" : filter.active;
            filter.category = String.IsNullOrEmpty(filter.category)? "" : filter.category;
            return aRepository.GetOperateLog(filter);
        }

        public object getFilterOption(){
            var category = aRepository.GetOpLogCategory();
            var userName = mRepository.GetAllPrincipal();
            return new {category, userName};
        }

        public int manual_refreshPunchLogWarn(int day=7){ //day:正整數 刷新前n天打卡紀錄
            var result = 0;
            try{
                chkWarn.start(day);
                result = 1;
            }catch (System.Exception){}
            return result;
        }

        public int manual_calWorkTime(int month=1){  //month:正整數 計算這個月與前n個月 預設為這個月與前1個月
            var result = 0;
            try{
                calTime.start(month);
                result = 1;
            }catch (System.Exception){}
            return result;
        }

        public int manual_calAnnualLeave(){
            var result = 0;
            try{
                calAnnual.start();
                result = 1;
            }catch (System.Exception){}
            return result;
        }

        public object clearEmployeeAnnualLeaves(int delMonth=36){   //清除舊的年假 以deadline做為判斷
             return processClearFn(delMonth, "annual");
        }
        
        public object clearEmployeeLeaveOfficeApply(int delMonth=36){    //清除舊請假紀錄 以createTime為判斷
            return processClearFn(delMonth, "leave");
        }

        public object clearPunchCardLogs(int delMonth=36){   //清除打卡 以logDate為判斷
            return processClearFn(delMonth, "punch");
        }

        public object clearOperateLogs(int delMonth=36){ //清除操作紀錄 以createTime為判斷
            return processClearFn(delMonth, "operate");
        }

        public object processClearFn(int delMonth, string sel){
            if(delMonth <= 5 || delMonth > 1200){         //至少要6個月以前
                return new{statusCode=0};
            }
            var dt = definePara.dtNow().Date;
            dt = dt.AddMonths(-delMonth);
            var count = 0;
            switch (sel){
                case "leave": count = aRepository.ClearEmployeeLeaveOfficeApply(dt); break;
                case "punch": count = aRepository.ClearPunchCardLogs(dt); break;
                case "operate": count = aRepository.ClearOperateLogs(dt); break;
                case "annual": count = aRepository.ClearEmployeeAnnualLeaves(dt); break;
                default: count = -1; break;
            }
            return new{statusCode=(count==-1? 0 : 1), count};
        }

        
        public object clearMessageAndMsgSendReceive(){ //清除訊息 需寄件人與收件人都刪除才可清除
            var count = aRepository.ClearMessageAndMsgSendReceive();
            return new{statusCode=(count==-1? 0 : 1), count};
        }

        public String deadLineLess1Second(){
            aRepository.DeadLineLess1Second();
            return "OK";
        }
        
    }

}

Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using practice_mvc02.filters;
using practice_mvc02.Models;
using practice_mvc02.Models.dataTable;
using practice_mvc02.Repositories;

namespace practice_mvc02.Controllers
{
    [TypeFilter(typeof(ActionFilter))]
    public class MessageController : BaseController
    {
        public MessageRepository Repository { get; }

        public MessageController(MessageRepository repository, IHttpContextAccessor httpContextAccessor):base(httpContextAccessor)
        {
            this.Repository = repository;
        }

        public IActionResult Index(string page="new")
        {           
            return selectPage(page);
            //return RedirectToAction("logOut", "Home"); //轉址到特定Controller的ACTION名字
        }

        public IActionResult selectPage(string page){
            ViewBag.ruleVal = ruleVal;
            ViewData["loginName"] = loginName;
            ViewBag.Auth = "Y";
            switch(page){
                case "new": ViewBag.Page = "new";break;
                case "all": ViewBag.Page = "all";break;
                //case "write": ViewBag.Page = "write";break;
                //case "backup": ViewBag.Page = "backup";break;
            }
            return View("MessagePage");  
        }

        //---------------------------------------------------------------------------------------
        
       
        #region  Message

        public object getReceiveMessage(int readStatus){
            return Repository.GetReceiveMessage((int)loginID, readStatus);
        }

        public object getSendMessage(){
            return Repository.GetSendMessage((int)loginID);
        }

        public int setHadReadMsg(int[] msgID){
            return Repository.SetHadReadMsg(msgID, (int)loginID);
        }

        public int delMessage(int[] msgID, string sel){
            return Repository.DelMessage(msgID, sel ,(int)loginID);
        }
        #endregion //Message

        //-----------------------------------------------------------------------------------------

        #region  write Message

        public object getReceiveOption(){           
            return Repository.GetReceiveOption();
        }

        public int sendMsg(Message msg, string depart, string receiveID){
            depart = String.IsNullOrEmpty(depart)? "" : depart;
            receiveID = String.IsNullOrEmpty(receiveID)? "" : receiveID;
            if((depart == "" || depart != "-1") && receiveID == ""){
                return 0;
            }
            msg.lastOperaAccID = (int)loginID;
            msg.createTime = definePara.dtNow();
            return Repository.createMessage(msg, depart, receiveID);
        }

        #endregion //write Message
        
    }
}

Controllers/SetRuleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using practice_mvc02.filters;
using practice_mvc02.Models;
using practice_mvc02.Models.dataTable;
using practice_mvc02.Repositories;

namespace practice_mvc02.Controllers
{
    [TypeFilter(typeof(ActionFilter))]
    public class SetRuleController : BaseController
    {
        //private readonly ILogger<HomeController> _logger;
        public SetRuleRepository Repository { get; }
        public punchCardFunction punchCardFn {get;}

        public SetRuleController(SetRuleRepository repository, punchCardFunction fn,
                                    IHttpContextAccessor httpContextAccessor):base(httpContextAccessor)
        {
            this.Repository = repository;
            this.punchCardFn = fn;
        }

        public IActionResult Index(string page)
        {           
            return selectPage(page);
        }

       public IActionResult selectPage(string page){
            ViewBag.ruleVal = ruleVal;
            ViewData["loginName"] = loginName;
            ViewBag.Auth = "Y";
            ViewBag.loginAccLV = loginAccLV;
            ViewBag.Page = page;
            return View("SetRulePage");
        }

       //--------------------------------------------------------------------------------------

        #region timeRule
        public object getAllTimeRule(){
           return Repository.GetAllTimeRule();
       }

        public dynamic addUpTimeRule(WorkTimeRule data){
            bool hasSame = Repository.chkSameWorkTime(data);
            bool isLegal = chkDataLegal(data);
            if(!isLegal){
                return "illegal";
            }
            var result = 0;
            data.lastOperaAccID = (int)loginID;
            if(data.ID==0){
                data.createTime = definePara.dtNow();
                result = Repository.AddTimeRule(data);
            }else{
                data.updateTime = definePara.dtNow();
                result = Repository.UpdateTimeRule(data);
            }
            if(hasSame && result == 1){
                return "same";
            }
            return result;
        }

        public int delTimeRule(int timeRuleID){
            return Repository.DelTimeRule(timeRuleID, (int)loginID);
        }

        public bool chkDataLegal(WorkTimeRule data){
            var wt = punchCardFn.workTimeProcess(data);
            var result = true;
            result = (wt.sWorkDt < wt.eWorkDt)? result : false;
            result = (wt.eWorkDt - wt.sWorkDt).TotalMinutes <=720? result : false;  //720mins = 12hours
            result = (wt.sRestDt > wt.sWorkDt && wt.sRestDt < wt.eWorkDt)? result : false;
            result = (wt.eRestDt > wt.sWorkDt && wt.eRestDt < wt.eWorkDt)? result : false;
            result = (wt.sRestDt <= wt.eRestDt)? result : false;
            return result;
        }

        #endregion //timeRule
        
        //-----------------------------------------------------------------------------------------------------

        #region GroupRule
        public object getAllGroup(){
            return Repository.GetAllGroup();
        }

        public int addGroup(GroupRule newGroup){
            newGroup.lastOperaAccID = (int)loginID;
            newGroup.createTime = definePara.dtNow();
            return Repository.AddGroup(newGroup);
        }

        public int delGroup(int groupID){
            return Repository.DelGroup(groupID, (int)loginID);
        }

        public int updateGroup(GroupRule updateGroup){
            updateGroup.lastOperaAccID = (int)loginID;
            updateGroup.updateTime = definePara.dtNow();
            return Repository.UpdateGroup(updateGroup);
        }

        #endregion  //GroupRule

        //-----------------------------------------------------------------------------------------------------

        #region specialDate
        
        public object getAllSpecialDate(){
            return Repository.GetAllSpecialDate();
        }

        public object getClassDepart(){
            return Repository.GetClassDepart();
        }

        public int addUpSpecialTime(SpecialDate spDate){
            spDate.lastOperaAccID = (int)loginID;
            if(spDate.ID == 0){     
                spDate.createTime = definePara.dtNow();
                return Repository.AddSpecialTime(spDate);
            }else{
                spDate.updateTime = definePara.dtNow();
                return Repository.UpdateSpecialTime(spDate);
            } 
        }

        public int delSpecialDate(int spDateID){
            return Repository.DelSpecialDate(spDateID, (int)loginID);
        }

        #endregion //specialDate

        //----------------------------------------------------------------------------------------------------------------------

        #region leaveTimeRule
        
        public object getAllLeaveRule(){
            return Repository.GetAllLeaveRule();
        }

        public int addUpLeave(LeaveName data){
            data.lastOperaAccID = (int)loginID;
            if(data.ID == 0){
               data.createTime = definePara.dtNow();
               return Repository.AddLeave(data);
            }else{
                data.updateTime = definePara.dtNow();
                return Repository.UpdateLeave(data);
            }
        }

        public int delLeave(int leaveID){
            return Repository.DelLeave(leaveID, (int)loginID);
        }

        #endregion //leaveTimeRule

        //------------------------------------------------------------------------------------------------------

        #region spLeaveRule

        public object getAllSpLeaveRule(){
            return Repository.GetAllSpLeaveRule();
        }

        public int addUpSpLeaveRule(AnnualLeaveRule data){
            data.lastOperaAccID = (int)loginID;
            if(data.ID == 0){
               data.createTime = definePara.dtNow();
               return Repository.AddSpLeaveRule(data);
            }else{
                data.updateTime = definePara.dtNow();
                return Repository.UpdateSpLeaveRule(data);
            }
        }

        public int delSpLeaveRule(int ruleID){
            return Repository.DelSpLeaveRule(ruleID, (int)loginID);
        }

        #endregion //spLeaveRule

        //------------------------------------------------------------------------------------------------------
        
    }
}

Views/Shared/_Layout.cshtml
@{
    bool baseBtn = (ViewBag.ruleVal & 0x0001)>0 ? true : false;
    bool employeeListBtn = (ViewBag.ruleVal & 0x0004)>0 || (ViewBag.ruleVal & 0x0008)>0 ? true : false;
    bool departListBtn = (ViewBag.ruleVal & 0x0020)>0 ? true : false; 
    bool applySignBtn = (ViewBag.ruleVal & 0x0080)>0 ? true : false; 
    bool setRuleBtn = (ViewBag.ruleVal & 0x0040)>0 ? true : false;
    bool adminBtn = (ViewBag.ruleVal & 0x0100)>0 ? true : false;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>打卡系統 - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap/bootstrap_css_4_4_1.css" />
    <link rel="stylesheet" href="~/css/my_style.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="#" style="pointer-events:none;">打卡系統</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">           
                    @if (ViewBag.Auth == "Y")
                    {       
                        @if(baseBtn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PunchCard" asp-action="Index">打卡</a>
                            </li>  
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplyOvertime" asp-action="Index">加班申請</a>
                            </li>  
                           <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplyLeave" asp-action="Index">請假申請</a>
                            </li>  
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeDetail" asp-action="Index">基本資料</a>
                        </li>
                        <li class="nav-item">
                            <a id="messageLink" class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">訊息</a>
                        </li>       
                        @if(employeeListBtn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeList" asp-action="Index">員工列表</a>
                            </li>
                        }
                        @if(applySignBtn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationSign" asp-action="Index">相關簽核</a>
                            </li>
                        }
                        @if(departListBtn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="DepartmentList" asp-action="Index">部門職位</a>
                            </li>
                        }
                        @if(setRuleBtn)
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="SetRule" asp-action="Index" asp-route-page="timeRule">設定規則</a>
                            </li>
                        }
                        @if(adminBtn)
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminFn" asp-action="Index">管理功能</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="logOut">登出</a>
                        </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2020 - practice_mvc02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div> *@
    </footer>
    <script src="~/js/api/jquery_3_4_1.js" type="text/javascript"></script>
    <script src="~/js/api/popper_1_16_1.js" type="text/javascript"></script>
    <script src="~/js/api/bootstrap_4_4_1.js" type="text/javascript"></script>    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>	
    <script src="~/js/baseNavBar.js" type="text/javascript"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>